#  Copyright (c) Microsoft Corporation.
#  Licensed under the MIT License.

import logging
import warnings
import pandas as pd
import numpy as np
from tqdm import trange
from pprint import pprint
from typing import Union, List, Optional, Dict
import os
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import rcParams

from qlib.utils.exceptions import LoadObjectError
from ..contrib.evaluate import risk_analysis, indicator_analysis

from ..data.dataset import DatasetH
from ..data.dataset.handler import DataHandlerLP
from ..backtest import backtest as normal_backtest
from ..log import get_module_logger
from ..utils import fill_placeholder, flatten_dict, class_casting, get_date_by_shift
from ..utils.time import Freq
from ..utils.data import deepcopy_basic_type
from ..utils.exceptions import QlibException
from ..contrib.eva.alpha import calc_ic, calc_long_short_return, calc_long_short_prec


logger = get_module_logger("workflow", logging.INFO)


class RecordTemp:
    """
    This is the Records Template class that enables user to generate experiment results such as IC and
    backtest in a certain format.
    """

    artifact_path = None
    depend_cls = None  # the dependant class of the record; the record will depend on the results generated by
    # `depend_cls`

    @classmethod
    def get_path(cls, path=None):
        names = []
        if cls.artifact_path is not None:
            names.append(cls.artifact_path)

        if path is not None:
            names.append(path)

        return "/".join(names)

    def save(self, **kwargs):
        """
        It behaves the same as self.recorder.save_objects.
        But it is an easier interface because users don't have to care about `get_path` and `artifact_path`
        """
        art_path = self.get_path()
        if art_path == "":
            art_path = None
        self.recorder.save_objects(artifact_path=art_path, **kwargs)

    def __init__(self, recorder):
        self._recorder = recorder

    @property
    def recorder(self):
        if self._recorder is None:
            raise ValueError("This RecordTemp did not set recorder yet.")
        return self._recorder

    def generate(self, **kwargs):
        """
        Generate certain records such as IC, backtest etc., and save them.

        Parameters
        ----------
        kwargs

        Return
        ------
        """
        raise NotImplementedError(f"Please implement the `generate` method.")

    def load(self, name: str, parents: bool = True):
        """
        It behaves the same as self.recorder.load_object.
        But it is an easier interface because users don't have to care about `get_path` and `artifact_path`

        Parameters
        ----------
        name : str
            the name for the file to be load.

        parents : bool
            Each recorder has different `artifact_path`.
            So parents recursively find the path in parents
            Sub classes has higher priority

        Return
        ------
        The stored records.
        """
        try:
            return self.recorder.load_object(self.get_path(name))
        except LoadObjectError as e:
            if parents:
                if self.depend_cls is not None:
                    with class_casting(self, self.depend_cls):
                        return self.load(name, parents=True)
            raise e

    def list(self):
        """
        List the supported artifacts.
        Users don't have to consider self.get_path

        Return
        ------
        A list of all the supported artifacts.
        """
        return []

    def check(self, include_self: bool = False, parents: bool = True):
        """
        Check if the records is properly generated and saved.
        It is useful in following examples

        - checking if the dependant files complete before generating new things.
        - checking if the final files is completed

        Parameters
        ----------
        include_self : bool
            is the file generated by self included
        parents : bool
            will we check parents

        Raise
        ------
        FileNotFoundError
            whether the records are stored properly.
        """
        if include_self:
            # Some mlflow backend will not list the directly recursively.
            # So we force to the directly
            artifacts = {}

            def _get_arts(dirn):
                if dirn not in artifacts:
                    artifacts[dirn] = self.recorder.list_artifacts(dirn)
                return artifacts[dirn]

            for item in self.list():
                ps = self.get_path(item).split("/")
                dirn = "/".join(ps[:-1])
                if self.get_path(item) not in _get_arts(dirn):
                    raise FileNotFoundError
        if parents:
            if self.depend_cls is not None:
                with class_casting(self, self.depend_cls):
                    self.check(include_self=True)


class SignalRecord(RecordTemp):
    """
    This is the Signal Record class that generates the signal prediction. This class inherits the ``RecordTemp`` class.
    """

    def __init__(self, model=None, dataset=None, recorder=None):
        super().__init__(recorder=recorder)
        self.model = model
        self.dataset = dataset

    @staticmethod
    def generate_label(dataset):
        with class_casting(dataset, DatasetH):
            params = dict(segments="test", col_set="label", data_key=DataHandlerLP.DK_R)
            try:
                # Assume the backend handler is DataHandlerLP
                raw_label = dataset.prepare(**params)
            except TypeError:
                # The argument number is not right
                del params["data_key"]
                # The backend handler should be DataHandler
                raw_label = dataset.prepare(**params)
            except AttributeError as e:
                # The data handler is initialized with `drop_raw=True`...
                # So raw_label is not available
                logger.warning(f"Exception: {e}")
                raw_label = None
        return raw_label

    def generate(self, **kwargs):
        # generate prediction
        pred = self.model.predict(self.dataset)
        if isinstance(pred, pd.Series):
            pred = pred.to_frame("score")
        self.save(**{"pred.pkl": pred})

        logger.info(
            f"Signal record 'pred.pkl' has been saved as the artifact of the Experiment {self.recorder.experiment_id}"
        )
        # print out results
        pprint(f"The following are prediction results of the {type(self.model).__name__} model.")
        pprint(pred.head(5))

        if isinstance(self.dataset, DatasetH):
            raw_label = self.generate_label(self.dataset)
            self.save(**{"label.pkl": raw_label})

    def list(self):
        return ["pred.pkl", "label.pkl"]


class ACRecordTemp(RecordTemp):
    """Automatically checking record template"""

    def __init__(self, recorder, skip_existing=False):
        self.skip_existing = skip_existing
        super().__init__(recorder=recorder)

    def generate(self, *args, **kwargs):
        """automatically checking the files and then run the concrete generating task"""
        if self.skip_existing:
            try:
                self.check(include_self=True, parents=False)
            except FileNotFoundError:
                pass  # continue to generating metrics
            else:
                logger.info("The results has previously generated, Generation skipped.")
                return

        try:
            self.check()
        except FileNotFoundError:
            logger.warning("The dependent data does not exists. Generation skipped.")
            return
        artifact_dict = self._generate(*args, **kwargs)
        if isinstance(artifact_dict, dict):
            self.save(**artifact_dict)
        return artifact_dict

    def _generate(self, *args, **kwargs) -> Dict[str, object]:
        """
        Run the concrete generating task, return the dictionary of the generated results.
        The caller method will save the results to the recorder.
        """
        raise NotImplementedError(f"Please implement the `_generate` method")


class HFSignalRecord(SignalRecord):
    """
    This is the Signal Analysis Record class that generates the analysis results such as IC and IR. This class inherits the ``RecordTemp`` class.
    """

    artifact_path = "hg_sig_analysis"
    depend_cls = SignalRecord

    def __init__(self, recorder, **kwargs):
        super().__init__(recorder=recorder)

    def generate(self):
        pred = self.load("pred.pkl")
        raw_label = self.load("label.pkl")
        long_pre, short_pre = calc_long_short_prec(pred.iloc[:, 0], raw_label.iloc[:, 0], is_alpha=True)
        ic, ric = calc_ic(pred.iloc[:, 0], raw_label.iloc[:, 0])
        metrics = {
            "IC": ic.mean(),
            "ICIR": ic.mean() / ic.std(),
            "Rank IC": ric.mean(),
            "Rank ICIR": ric.mean() / ric.std(),
            "Long precision": long_pre.mean(),
            "Short precision": short_pre.mean(),
        }
        objects = {"ic.pkl": ic, "ric.pkl": ric}
        objects.update({"long_pre.pkl": long_pre, "short_pre.pkl": short_pre})
        long_short_r, long_avg_r = calc_long_short_return(pred.iloc[:, 0], raw_label.iloc[:, 0])
        metrics.update(
            {
                "Long-Short Average Return": long_short_r.mean(),
                "Long-Short Average Sharpe": long_short_r.mean() / long_short_r.std(),
            }
        )
        objects.update(
            {
                "long_short_r.pkl": long_short_r,
                "long_avg_r.pkl": long_avg_r,
            }
        )
        self.recorder.log_metrics(**metrics)
        self.save(**objects)
        pprint(metrics)

    def list(self):
        return ["ic.pkl", "ric.pkl", "long_pre.pkl", "short_pre.pkl", "long_short_r.pkl", "long_avg_r.pkl"]


class SigAnaRecord(ACRecordTemp):
    """
    This is the Signal Analysis Record class that generates the analysis results such as IC and IR.
    This class inherits the ``RecordTemp`` class.
    """

    artifact_path = "sig_analysis"
    depend_cls = SignalRecord

    def __init__(self, recorder, ana_long_short=False, ann_scaler=252, label_col=0, skip_existing=False):
        super().__init__(recorder=recorder, skip_existing=skip_existing)
        self.ana_long_short = ana_long_short
        self.ann_scaler = ann_scaler
        self.label_col = label_col

    def _generate(self, label: Optional[pd.DataFrame] = None, **kwargs):
        """
        Parameters
        ----------
        label : Optional[pd.DataFrame]
            Label should be a dataframe.
        """
        pred = self.load("pred.pkl")
        if label is None:
            label = self.load("label.pkl")
        if label is None or not isinstance(label, pd.DataFrame) or label.empty:
            logger.warning(f"Empty label.")
            return
        ic, ric = calc_ic(pred.iloc[:, 0], label.iloc[:, self.label_col])
        metrics = {
            "IC": ic.mean(),
            "ICIR": ic.mean() / ic.std(),
            "Rank IC": ric.mean(),
            "Rank ICIR": ric.mean() / ric.std(),
        }
        objects = {"ic.pkl": ic, "ric.pkl": ric}
        if self.ana_long_short:
            long_short_r, long_avg_r = calc_long_short_return(pred.iloc[:, 0], label.iloc[:, self.label_col])
            metrics.update(
                {
                    "Long-Short Ann Return": long_short_r.mean() * self.ann_scaler,
                    "Long-Short Ann Sharpe": long_short_r.mean() / long_short_r.std() * self.ann_scaler**0.5,
                    "Long-Avg Ann Return": long_avg_r.mean() * self.ann_scaler,
                    "Long-Avg Ann Sharpe": long_avg_r.mean() / long_avg_r.std() * self.ann_scaler**0.5,
                }
            )
            objects.update(
                {
                    "long_short_r.pkl": long_short_r,
                    "long_avg_r.pkl": long_avg_r,
                }
            )
        self.recorder.log_metrics(**metrics)
        pprint(metrics)
        return objects

    def list(self):
        paths = ["ic.pkl", "ric.pkl"]
        if self.ana_long_short:
            paths.extend(["long_short_r.pkl", "long_avg_r.pkl"])
        return paths


class PortAnaRecord(ACRecordTemp):
    """
    This is the Portfolio Analysis Record class that generates the analysis results such as those of backtest. This class inherits the ``RecordTemp`` class.

    The following files will be stored in recorder

    - report_normal.pkl & positions_normal.pkl:

        - The return report and detailed positions of the backtest, returned by `qlib/contrib/evaluate.py:backtest`
    - port_analysis.pkl : The risk analysis of your portfolio, returned by `qlib/contrib/evaluate.py:risk_analysis`
    """

    artifact_path = "portfolio_analysis"
    depend_cls = SignalRecord

    def __init__(
        self,
        recorder,
        config=None,
        risk_analysis_freq: Union[List, str] = None,
        indicator_analysis_freq: Union[List, str] = None,
        indicator_analysis_method=None,
        skip_existing=False,
        **kwargs,
    ):
        """
        config["strategy"] : dict
            define the strategy class as well as the kwargs.
        config["executor"] : dict
            define the executor class as well as the kwargs.
        config["backtest"] : dict
            define the backtest kwargs.
        risk_analysis_freq : str|List[str]
            risk analysis freq of report
        indicator_analysis_freq : str|List[str]
            indicator analysis freq of report
        indicator_analysis_method : str, optional, default by None
            the candidate values include 'mean', 'amount_weighted', 'value_weighted'
        """
        super().__init__(recorder=recorder, skip_existing=skip_existing, **kwargs)

        if config is None:
            config = {  # Default config for daily trading
                "strategy": {
                    "class": "TopkDropoutStrategy",
                    "module_path": "qlib.contrib.strategy",
                    "kwargs": {"signal": "<PRED>", "topk": 50, "n_drop": 5},
                },
                "backtest": {
                    "start_time": None,
                    "end_time": None,
                    "account": 100000000,
                    "benchmark": "SH000300",
                    "exchange_kwargs": {
                        "limit_threshold": 0.095,
                        "deal_price": "close",
                        "open_cost": 0.0005,
                        "close_cost": 0.0015,
                        "min_cost": 5,
                    },
                },
            }
        # We only deepcopy_basic_type because
        # - We don't want to affect the config outside.
        # - We don't want to deepcopy complex object to avoid overhead
        config = deepcopy_basic_type(config)

        self.strategy_config = config["strategy"]
        _default_executor_config = {
            "class": "SimulatorExecutor",
            "module_path": "qlib.backtest.executor",
            "kwargs": {
                "time_per_step": "day",
                "generate_portfolio_metrics": True,
            },
        }
        self.executor_config = config.get("executor", _default_executor_config)
        self.backtest_config = config["backtest"]

        self.all_freq = self._get_report_freq(self.executor_config)
        if risk_analysis_freq is None:
            risk_analysis_freq = [self.all_freq[0]]
        if indicator_analysis_freq is None:
            indicator_analysis_freq = [self.all_freq[0]]

        if isinstance(risk_analysis_freq, str):
            risk_analysis_freq = [risk_analysis_freq]
        if isinstance(indicator_analysis_freq, str):
            indicator_analysis_freq = [indicator_analysis_freq]

        self.risk_analysis_freq = [
            "{0}{1}".format(*Freq.parse(_analysis_freq)) for _analysis_freq in risk_analysis_freq
        ]
        self.indicator_analysis_freq = [
            "{0}{1}".format(*Freq.parse(_analysis_freq)) for _analysis_freq in indicator_analysis_freq
        ]
        self.indicator_analysis_method = indicator_analysis_method

    def _get_report_freq(self, executor_config):
        ret_freq = []
        if executor_config["kwargs"].get("generate_portfolio_metrics", False):
            _count, _freq = Freq.parse(executor_config["kwargs"]["time_per_step"])
            ret_freq.append(f"{_count}{_freq}")
        if "inner_executor" in executor_config["kwargs"]:
            ret_freq.extend(self._get_report_freq(executor_config["kwargs"]["inner_executor"]))
        return ret_freq

    def _generate(self, **kwargs):
        pred = self.load("pred.pkl")

        # replace the "<PRED>" with prediction saved before
        placeholder_value = {"<PRED>": pred}
        for k in "executor_config", "strategy_config":
            setattr(self, k, fill_placeholder(getattr(self, k), placeholder_value))

        # if the backtesting time range is not set, it will automatically extract time range from the prediction file
        dt_values = pred.index.get_level_values("datetime")
        if self.backtest_config["start_time"] is None:
            self.backtest_config["start_time"] = dt_values.min()
        if self.backtest_config["end_time"] is None:
            self.backtest_config["end_time"] = get_date_by_shift(dt_values.max(), 1)

        artifact_objects = {}
        # custom strategy and get backtest
        portfolio_metric_dict, indicator_dict = normal_backtest(
            executor=self.executor_config, strategy=self.strategy_config, **self.backtest_config
        )
        for _freq, (report_normal, positions_normal) in portfolio_metric_dict.items():
            artifact_objects.update({f"report_normal_{_freq}.pkl": report_normal})
            artifact_objects.update({f"positions_normal_{_freq}.pkl": positions_normal})

        for _freq, indicators_normal in indicator_dict.items():
            artifact_objects.update({f"indicators_normal_{_freq}.pkl": indicators_normal[0]})
            artifact_objects.update({f"indicators_normal_{_freq}_obj.pkl": indicators_normal[1]})

        for _analysis_freq in self.risk_analysis_freq:
            if _analysis_freq not in portfolio_metric_dict:
                warnings.warn(
                    f"the freq {_analysis_freq} report is not found, please set the corresponding env with `generate_portfolio_metrics=True`"
                )
            else:
                report_normal, _ = portfolio_metric_dict.get(_analysis_freq)
                analysis = dict()
                analysis["excess_return_without_cost"] = risk_analysis(
                    report_normal["return"] - report_normal["bench"], freq=_analysis_freq
                )
                analysis["excess_return_with_cost"] = risk_analysis(
                    report_normal["return"] - report_normal["bench"] - report_normal["cost"], freq=_analysis_freq
                )
                analysis["return_with_cost"] = risk_analysis(
                    report_normal["return"] - report_normal["cost"], freq=_analysis_freq, mode="product"
                )
                analysis["return_without_cost"] = risk_analysis(
                    report_normal["return"], freq=_analysis_freq, mode="product"
                )

                analysis_df = pd.concat(analysis)  # type: pd.DataFrame
                # log metrics
                analysis_dict = flatten_dict(analysis_df["risk"].unstack().T.to_dict())
                self.recorder.log_metrics(**{f"{_analysis_freq}.{k}": v for k, v in analysis_dict.items()})
                # save results
                artifact_objects.update({f"port_analysis_{_analysis_freq}.pkl": analysis_df})
                logger.info(
                    f"Portfolio analysis record 'port_analysis_{_analysis_freq}.pkl' has been saved as the artifact of the Experiment {self.recorder.experiment_id}"
                )
                # print out results
                pprint(f"The following are analysis results of benchmark return({_analysis_freq}).")
                pprint(risk_analysis(report_normal["bench"], freq=_analysis_freq, mode="product"))
                pprint(f"The following are analysis results of the excess return without cost({_analysis_freq}).")
                pprint(analysis["excess_return_without_cost"])
                pprint(f"The following are analysis results of the excess return with cost({_analysis_freq}).")
                pprint(analysis["excess_return_with_cost"])
                pprint(f"The following are analysis results of the return without cost({_analysis_freq}).")
                pprint(analysis["return_without_cost"])
                pprint(f"The following are analysis results of the return with cost({_analysis_freq}).")
                pprint(analysis["return_with_cost"])

        for _analysis_freq in self.indicator_analysis_freq:
            if _analysis_freq not in indicator_dict:
                warnings.warn(f"the freq {_analysis_freq} indicator is not found")
            else:
                indicators_normal = indicator_dict.get(_analysis_freq)[0]
                if self.indicator_analysis_method is None:
                    analysis_df = indicator_analysis(indicators_normal)
                else:
                    analysis_df = indicator_analysis(indicators_normal, method=self.indicator_analysis_method)
                # append turnover metrics from report_normal
                if _analysis_freq in portfolio_metric_dict:
                    report_normal, _ = portfolio_metric_dict.get(_analysis_freq)
                    avg_turnover_rate = report_normal["turnover"].mean()
                    rebalance_day_ratio = (report_normal["turnover"] != 0).sum() / len(report_normal)
                    extra_metrics = pd.DataFrame(
                        {"value": {"avg_turnover_rate": avg_turnover_rate, "rebalance_day_ratio": rebalance_day_ratio}}
                    )
                    analysis_df = pd.concat([analysis_df, extra_metrics])
                # log metrics
                analysis_dict = analysis_df["value"].to_dict()
                self.recorder.log_metrics(**{f"{_analysis_freq}.{k}": v for k, v in analysis_dict.items()})
                # save results
                artifact_objects.update({f"indicator_analysis_{_analysis_freq}.pkl": analysis_df})
                logger.info(
                    f"Indicator analysis record 'indicator_analysis_{_analysis_freq}.pkl' has been saved as the artifact of the Experiment {self.recorder.experiment_id}"
                )
                pprint(f"The following are analysis results of indicators({_analysis_freq}).")
                pprint(analysis_df)
        return artifact_objects

    def list(self):
        list_path = []
        for _freq in self.all_freq:
            list_path.extend(
                [
                    f"report_normal_{_freq}.pkl",
                    f"positions_normal_{_freq}.pkl",
                ]
            )
        for _analysis_freq in self.risk_analysis_freq:
            if _analysis_freq in self.all_freq:
                list_path.append(f"port_analysis_{_analysis_freq}.pkl")
            else:
                warnings.warn(f"risk_analysis freq {_analysis_freq} is not found")

        for _analysis_freq in self.indicator_analysis_freq:
            if _analysis_freq in self.all_freq:
                list_path.append(f"indicator_analysis_{_analysis_freq}.pkl")
            else:
                warnings.warn(f"indicator_analysis freq {_analysis_freq} is not found")
        return list_path


class MultiPassPortAnaRecord(PortAnaRecord):
    """
    This is the Multiple Pass Portfolio Analysis Record class that run backtest multiple times and generates the analysis results such as those of backtest. This class inherits the ``PortAnaRecord`` class.

    If shuffle_init_score enabled, the prediction score of the first backtest date will be shuffled, so that initial position will be random.
    The shuffle_init_score will only works when the signal is used as <PRED> placeholder. The placeholder will be replaced by pred.pkl saved in recorder.

    Parameters
    ----------
    recorder : Recorder
        The recorder used to save the backtest results.
    pass_num : int
        The number of backtest passes.
    shuffle_init_score : bool
        Whether to shuffle the prediction score of the first backtest date.
    """

    depend_cls = SignalRecord

    def __init__(self, recorder, pass_num=10, shuffle_init_score=True, **kwargs):
        """
        Parameters
        ----------
        recorder : Recorder
            The recorder used to save the backtest results.
        pass_num : int
            The number of backtest passes.
        shuffle_init_score : bool
            Whether to shuffle the prediction score of the first backtest date.
        """
        self.pass_num = pass_num
        self.shuffle_init_score = shuffle_init_score

        super().__init__(recorder, **kwargs)

        # Save original strategy so that pred df can be replaced in next generate
        self.original_strategy = deepcopy_basic_type(self.strategy_config)
        if not isinstance(self.original_strategy, dict):
            raise QlibException("MultiPassPortAnaRecord require the passed in strategy to be a dict")
        if "signal" not in self.original_strategy.get("kwargs", {}):
            raise QlibException("MultiPassPortAnaRecord require the passed in strategy to have signal as a parameter")

    def random_init(self):
        pred_df = self.load("pred.pkl")

        all_pred_dates = pred_df.index.get_level_values("datetime")
        bt_start_date = pd.to_datetime(self.backtest_config.get("start_time"))
        if bt_start_date is None:
            first_bt_pred_date = all_pred_dates.min()
        else:
            first_bt_pred_date = all_pred_dates[all_pred_dates >= bt_start_date].min()

        # Shuffle the first backtest date's pred score
        first_date_score = pred_df.loc[first_bt_pred_date]["score"]
        np.random.shuffle(first_date_score.values)

        # Use shuffled signal as the strategy signal
        self.strategy_config = deepcopy_basic_type(self.original_strategy)
        self.strategy_config["kwargs"]["signal"] = pred_df

    def _generate(self, **kwargs):
        risk_analysis_df_map = {}

        # Collect each frequency's analysis df as df list
        for i in trange(self.pass_num):
            if self.shuffle_init_score:
                self.random_init()

            # Not check for cache file list
            single_run_artifacts = super()._generate(**kwargs)

            for _analysis_freq in self.risk_analysis_freq:
                risk_analysis_df_list = risk_analysis_df_map.get(_analysis_freq, [])
                risk_analysis_df_map[_analysis_freq] = risk_analysis_df_list

                analysis_df = single_run_artifacts[f"port_analysis_{_analysis_freq}.pkl"]
                analysis_df["run_id"] = i
                risk_analysis_df_list.append(analysis_df)

        result_artifacts = {}
        # Concat df list
        for _analysis_freq in self.risk_analysis_freq:
            combined_df = pd.concat(risk_analysis_df_map[_analysis_freq])

            # Calculate return and information ratio's mean, std and mean/std
            multi_pass_port_analysis_df = combined_df.groupby(level=[0, 1], group_keys=False).apply(
                lambda x: pd.Series(
                    {"mean": x["risk"].mean(), "std": x["risk"].std(), "mean_std": x["risk"].mean() / x["risk"].std()}
                )
            )

            # Only look at "annualized_return" and "information_ratio"
            multi_pass_port_analysis_df = multi_pass_port_analysis_df.loc[
                (slice(None), ["annualized_return", "information_ratio"]), :
            ]
            pprint(multi_pass_port_analysis_df)

            # Save new df
            result_artifacts.update({f"multi_pass_port_analysis_{_analysis_freq}.pkl": multi_pass_port_analysis_df})

            # Log metrics
            metrics = flatten_dict(
                {
                    "mean": multi_pass_port_analysis_df["mean"].unstack().T.to_dict(),
                    "std": multi_pass_port_analysis_df["std"].unstack().T.to_dict(),
                    "mean_std": multi_pass_port_analysis_df["mean_std"].unstack().T.to_dict(),
                }
            )
            self.recorder.log_metrics(**metrics)
        return result_artifacts

    def list(self):
        list_path = []
        for _analysis_freq in self.risk_analysis_freq:
            if _analysis_freq in self.all_freq:
                list_path.append(f"multi_pass_port_analysis_{_analysis_freq}.pkl")
            else:
                warnings.warn(f"risk_analysis freq {_analysis_freq} is not found")
        return list_path


def _export_figure_with_timeout(fig, save_path, timeout) -> bool:
    """在进程内导出图片并加线程级超时，避免 write_image 意外阻塞拖垮整体。

    使用 daemon 线程执行 write_image：
    - 进程内执行可复用 kaleido 常驻 Chromium（仅首图需启动），后续图片导出很快；
    - join(timeout) 超时则放弃该图（daemon 线程不阻塞进程退出）。
    返回 True 表示导出成功；超时或失败返回 False（不抛出，保证主流程继续）。
    """
    import threading

    result = {"ok": False, "error": None}

    def _worker():
        try:
            fig.write_image(save_path)
            result["ok"] = True
        except Exception as e:  # noqa: BLE001
            result["error"] = e

    t = threading.Thread(target=_worker, daemon=True)
    t.start()
    t.join(timeout)
    if t.is_alive():
        logger.warning(
            f"Figure export TIMEOUT (>{timeout}s): {save_path}. "
            f"Possible causes: kaleido not installed (`pip install kaleido`), "
            f"Chromium startup delay, or figure complexity."
        )
        return False
    if result["error"] is not None:
        logger.warning(
            f"Figure export FAILED for {save_path}: {result['error']}. "
            f"Check if kaleido is installed (`pip install kaleido`)."
        )
        return False
    return True


class ReportRecord(RecordTemp):
    """
    This is the Report Record class that generates analysis figures and CSVs.
    It covers the functionalities of draw_analysis_figures:
    - Save CSVs (pred, report, analysis)
    - report_graph: return curve
    - risk_analysis_graph: risk analysis
    - score_ic_graph: IC analysis
    - model_performance_graph: model performance

    This class inherits the ``RecordTemp`` class.
    """

    artifact_path = "report"

    def __init__(
        self,
        recorder,
        dataset=None,
        freq="1day",
        figure_timeout=60,
        **kwargs,
    ):
        super().__init__(recorder=recorder)
        self.dataset = dataset
        self.freq = freq
        # 单张图片导出(kaleido/write_image)的超时秒数，超时则跳过该图，避免整体卡死
        self.figure_timeout = int(figure_timeout)

    def generate(self, **kwargs):
        self._generate(**kwargs)

    def _generate(self, **kwargs):
        import os
        from qlib.contrib.report import analysis_model, analysis_position

        pred_df = self.recorder.load_object("pred.pkl")
        report_normal_df = self.recorder.load_object(f"portfolio_analysis/report_normal_{self.freq}.pkl")
        positions = self.recorder.load_object(f"portfolio_analysis/positions_normal_{self.freq}.pkl")
        analysis_df = self.recorder.load_object(f"portfolio_analysis/port_analysis_{self.freq}.pkl")

        artifact_objects = {}

        # Save CSVs
        artifact_uri = str(self.recorder.artifact_uri).replace("file://", "")
        save_root = os.path.join(artifact_uri, "analysis_csvs")
        os.makedirs(save_root, exist_ok=True)

        csv_dict = {
            "pred_df": pred_df,
            "report_normal_df": report_normal_df,
            "analysis_df": analysis_df,
        }
        for csv_type, csv_data in csv_dict.items():
            save_path = os.path.join(save_root, f"{csv_type}.csv")
            csv_data.to_csv(save_path, index=True)
            logger.info(f"Save {csv_type} to local file: {save_path}")

        # indicator analysis metrics CSV: computed from already-loaded report_normal_df, no extra pkl reads
        avg_turnover_rate = report_normal_df["turnover"].mean()
        rebalance_day_ratio = (report_normal_df["turnover"] != 0).sum() / len(report_normal_df)
        indicator_analysis_df = pd.DataFrame(
            {"value": {"avg_turnover_rate": avg_turnover_rate, "rebalance_day_ratio": rebalance_day_ratio}}
        )
        indicator_analysis_csv_path = os.path.join(save_root, "indicator_analysis_df.csv")
        indicator_analysis_df.to_csv(indicator_analysis_csv_path, index=True)
        logger.info(f"Save indicator_analysis_df to local file: {indicator_analysis_csv_path}")

        # 每日持仓明细 CSV: 每行为一天，每列为一只股票/cash 的当日持仓总价值，最后一列 account_value
        positions_rows = {}
        for date, pos_obj in positions.items():
            pos_dict = pos_obj.position
            account_value = pos_dict.get("now_account_value", float("nan"))
            cash = pos_dict.get("cash", float("nan"))
            row = {}
            for instrument, info in pos_dict.items():
                if instrument in ("cash_delay", "now_account_value"):
                    continue
                if instrument == "cash":
                    row["cash"] = cash
                elif isinstance(info, dict):
                    amount = info.get("amount", float("nan"))
                    price = info.get("price", float("nan"))
                    row[instrument] = amount * price
            row["account_value"] = account_value
            positions_rows[date] = row
        if positions_rows:
            positions_df = pd.DataFrame.from_dict(positions_rows, orient="index")
            positions_df.index.name = "date"
            # 把 cash 和 account_value 移到最后两列,其余按列名排序
            fixed_cols = [c for c in ("account_value") if c in positions_df.columns]
            stock_cols = sorted(c for c in positions_df.columns if c not in fixed_cols)
            positions_df = positions_df[stock_cols + fixed_cols]
            
            # 计算总持有率：每只基金的平均持仓占比（排除cash和account_value列）
            total_holding_ratio = {}
            for col in stock_cols:
                # 计算该基金每天的持仓占比（持仓价值/总账户价值）
                ratio_series = positions_df[col] / positions_df["account_value"]
                # 计算平均持仓占比
                total_holding_ratio[col] = ratio_series.mean()
            # 添加fixed_cols的占位值
            for col in fixed_cols:
                total_holding_ratio[col] = float("nan")
            
            # 将总持有率作为新行添加到DataFrame
            total_holding_df = pd.DataFrame([total_holding_ratio], index=["total_holding_ratio"])
            positions_df = pd.concat([positions_df, total_holding_df])
            
            positions_csv_path = os.path.join(save_root, "positions_daily.csv")
            positions_df.to_csv(positions_csv_path)
            logger.info(f"Save positions_daily to local file: {positions_csv_path}")

        # analysis position
        # report
        fig_list_return = analysis_position.report_graph(report_normal_df, show_notebook=False)

        # risk analysis
        fig_list_risk = analysis_position.risk_analysis_graph(analysis_df, report_normal_df, show_notebook=False)

        # analysis model
        label_df = None
        if self.dataset is not None:
            try:
                label_df = self.dataset.prepare("test", col_set="label")
                label_df.columns = ["label"]
            except Exception as e:
                logger.warning(f"Failed to prepare label data: {e}")

        fig_list_score_ic = []
        fig_list_model_performance = []
        if label_df is not None:
            pred_label = pd.concat([label_df, pred_df], axis=1, sort=True).reindex(label_df.index)

            # score IC
            fig_list_score_ic = analysis_position.score_ic_graph(pred_label, show_notebook=False)

            # model performance
            try:
                fig_list_model_performance = analysis_model.model_performance_graph(pred_label, show_notebook=False)
            except Exception as e:
                logger.warning(f"Model performance figure generation failed: {e}")
                fig_list_model_performance = []

        fig_dict = {
            "return": fig_list_return,
            "risk": fig_list_risk,
            "score_ic": fig_list_score_ic,
            "model_performance": fig_list_model_performance,
        }
        save_root = os.path.join(artifact_uri, "analysis_figures")
        os.makedirs(save_root, exist_ok=True)
        for fig_type, _fig_list in fig_dict.items():
            for idx, _fig in enumerate(_fig_list):
                save_path = os.path.join(save_root, f"{fig_type}_{idx}.png")
                if _export_figure_with_timeout(_fig, save_path, self.figure_timeout):
                    logger.info(f"Save figure to local file: {save_path}")
                else:
                    logger.warning(
                        f"Figure export timed out (>{self.figure_timeout}s) or failed, "
                        f"skipped: {save_path}"
                    )

        return artifact_objects

    def list(self):
        return []


# ---------------------------------------------------------------------------
# 辅助函数
# ---------------------------------------------------------------------------

def _fill_score_background(ax, dates, score_s, alpha: float = 0.12) -> None:
    """在 ax 上按 score 值填充背景色（+1=绿，-1=红）"""
    dates_arr = np.array(dates)
    score_arr = score_s.reindex(dates).fillna(0).values
    i = 0
    while i < len(dates_arr):
        s = score_arr[i]
        if s == 0:
            i += 1
            continue
        color = "#4CAF50" if s > 0 else "#F44336"
        j = i + 1
        while j < len(dates_arr) and score_arr[j] == s:
            j += 1
        ax.axvspan(dates_arr[i], dates_arr[j - 1], color=color, alpha=alpha)
        i = j


class MACDSignalChartRecord(ACRecordTemp):
    """
    MACD 信号概览图 Record

    将所有股票汇聚到一张大图中，每只股票占一个子图（价格与 MACD 合并、双 y 轴）：
      - 左轴：收盘价 + EMA_fast/EMA_slow 折线 + score 背景着色（+1=绿，-1=红）
      - 右轴：DIF/DEA 折线 + Histogram 柱状图

    生成文件：macd_signal_chart/macd_overview.png
    """

    artifact_path = "macd_signal_chart"
    depend_cls = SignalRecord

    def __init__(self, recorder, dataset=None, skip_existing=False):
        super().__init__(recorder=recorder, skip_existing=skip_existing)
        self.dataset = dataset

    def _generate(self, **kwargs):
        rcParams["font.sans-serif"] = ["Arial Unicode MS", "SimHei", "DejaVu Sans"]
        rcParams["axes.unicode_minus"] = False

        pred_df = self.load("pred.pkl")
        if pred_df.empty:
            logger.warning("MACDSignalChartRecord: pred.pkl is empty, skip.")
            return {}

        # 从 dataset 加载收盘价（test segment）
        close_wide: pd.DataFrame | None = None
        if self.dataset is not None:
            try:
                feat = self.dataset.prepare("test", col_set="feature", data_key=DataHandlerLP.DK_I)
                if "close" in feat.columns:
                    close_wide = feat["close"].unstack(level="instrument")
            except Exception as e:
                logger.warning(f"MACDSignalChartRecord: Failed to load close prices: {e}")

        instruments = sorted(pred_df.index.get_level_values("instrument").unique())
        n = len(instruments)
        if n == 0:
            logger.warning("MACDSignalChartRecord: no instruments found.")
            return {}

        # 布局：每行最多 ncols 只股票，每只股票占 1 个子图（价格与 MACD 合并、双 y 轴）
        ncols = min(4, n)
        n_inst_rows = (n + ncols - 1) // ncols
        nrows = n_inst_rows

        fig_w = max(5 * ncols, 12)
        fig_h = max(3 * nrows, 6)
        fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(fig_w, fig_h), squeeze=False)
        fig.suptitle("MACD 信号总览（左轴 价格/EMA，右轴 DIF/DEA/Histogram）", fontsize=13)

        for i, inst in enumerate(instruments):
            inst_row = i // ncols
            col = i % ncols
            ax_p = axes[inst_row][col]        # 左轴：价格 / EMA
            ax_m = ax_p.twinx()               # 右轴：MACD

            inst_pred = pred_df.xs(inst, level="instrument")
            dates = inst_pred.index

            price_handles = []

            # --- 左轴：收盘价 + EMA_fast/EMA_slow ---
            if close_wide is not None and inst in close_wide.columns:
                h, = ax_p.plot(dates, close_wide[inst].reindex(dates),
                               color="#212121", linewidth=0.25, label="Close")
                price_handles.append((h, "Close"))
            if "ema_fast" in inst_pred.columns:
                h, = ax_p.plot(dates, inst_pred["ema_fast"], color="#00ACC1",
                               linewidth=0.175, alpha=0.85, label="EMA_fast")
                price_handles.append((h, "EMA_fast"))
            if "ema_slow" in inst_pred.columns:
                h, = ax_p.plot(dates, inst_pred["ema_slow"], color="#E91E63",
                               linewidth=0.175, alpha=0.85, label="EMA_slow")
                price_handles.append((h, "EMA_slow"))

            # --- 左轴：score 背景着色 ---
            if "score" in inst_pred.columns:
                _fill_score_background(ax_p, dates, inst_pred["score"])

            ax_p.set_title(inst.replace("_CLEAN", ""), fontsize=8, pad=2)
            ax_p.set_ylabel("Price/EMA", fontsize=6)
            ax_p.tick_params(labelsize=5)
            ax_p.set_zorder(ax_m.get_zorder() + 1)   # 价格线置于 MACD 之上
            ax_p.patch.set_visible(False)            # 让右轴内容可见
            ax_p.xaxis.set_major_formatter(mdates.DateFormatter("%y-%m"))
            ax_p.xaxis.set_major_locator(mdates.AutoDateLocator())
            plt.setp(ax_p.xaxis.get_majorticklabels(), rotation=45, ha="right", fontsize=4)

            # --- 右轴：MACD (Histogram + DIF / DEA) ---
            macd_handles = []
            if "histogram" in inst_pred.columns:
                hist = inst_pred["histogram"]
                bar_colors = ["#4CAF50" if v >= 0 else "#F44336" for v in hist]
                ax_m.bar(dates, hist, color=bar_colors, alpha=0.4, width=1.5)
            if "dif" in inst_pred.columns:
                h, = ax_m.plot(dates, inst_pred["dif"], color="#3949AB", linewidth=0.2, label="DIF")
                macd_handles.append((h, "DIF"))
            if "dea" in inst_pred.columns:
                h, = ax_m.plot(dates, inst_pred["dea"], color="#FF9800", linewidth=0.2, label="DEA")
                macd_handles.append((h, "DEA"))
            ax_m.axhline(0, color="black", linewidth=0.4, alpha=0.5)
            ax_m.set_ylabel("MACD", fontsize=6)
            ax_m.tick_params(labelsize=5)

            # 每个子图都绘制图例
            all_h = price_handles + macd_handles
            if all_h:
                ax_p.legend([h for h, _ in all_h], [lb for _, lb in all_h],
                            fontsize=5, loc="upper left")

        # 隐藏多余子图
        for i in range(n, n_inst_rows * ncols):
            inst_row = i // ncols
            col = i % ncols
            axes[inst_row][col].set_visible(False)

        plt.tight_layout()

        artifact_uri = str(self.recorder.artifact_uri).replace("file://", "")
        save_root = os.path.join(artifact_uri, self.artifact_path)
        os.makedirs(save_root, exist_ok=True)
        save_path = os.path.join(save_root, "macd_overview.png")
        fig.savefig(save_path, dpi=120, bbox_inches="tight")
        plt.close(fig)
        logger.info(f"MACDSignalChartRecord: saved overview chart → {save_path}")
        return {}

    def list(self):
        return []


class EMValChartRecord(ACRecordTemp):
    """
    EMVal 信号概览图 Record

    将所有股票汇聚到一张大图中，每只股票占一个子图（价格与估值/趋势合并、双 y 轴）：
      - 左轴：收盘价 + EMA_fast/EMA_mid/EMA_slow 折线 + score 背景着色（+1=绿，-1=红）
      - 右轴：diff（趋势线）、over_val_pct（估值溢价率）、over_val_rank（估值分位）+ 买入/卖出阈值线

    生成文件：emval_chart/emval_overview.png
    """

    artifact_path = "emval_chart"
    depend_cls = SignalRecord

    def __init__(self, recorder, dataset=None, skip_existing=False,
                 buy_rank_thre=0.05, sell_rank_thre=0.75):
        super().__init__(recorder=recorder, skip_existing=skip_existing)
        self.dataset = dataset
        self.buy_rank_thre = buy_rank_thre
        self.sell_rank_thre = sell_rank_thre

    def _generate(self, **kwargs):
        rcParams["font.sans-serif"] = ["Arial Unicode MS", "SimHei", "DejaVu Sans"]
        rcParams["axes.unicode_minus"] = False

        pred_df = self.load("pred.pkl")
        if pred_df.empty:
            logger.warning("EMValChartRecord: pred.pkl is empty, skip.")
            return {}

        # 从 dataset 加载收盘价（test segment）
        close_wide: pd.DataFrame | None = None
        if self.dataset is not None:
            try:
                feat = self.dataset.prepare("test", col_set="feature", data_key=DataHandlerLP.DK_I)
                if "close" in feat.columns:
                    close_wide = feat["close"].unstack(level="instrument")
            except Exception as e:
                logger.warning(f"EMValChartRecord: Failed to load close prices: {e}")

        instruments = sorted(pred_df.index.get_level_values("instrument").unique())
        n = len(instruments)
        if n == 0:
            logger.warning("EMValChartRecord: no instruments found.")
            return {}

        # 布局：每行最多 ncols 只股票，每只股票占 1 个子图（价格与估值/趋势合并、双 y 轴）
        ncols = min(4, n)
        n_inst_rows = (n + ncols - 1) // ncols
        nrows = n_inst_rows

        fig_w = max(5 * ncols, 12)
        fig_h = max(3 * nrows, 6)
        fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(fig_w, fig_h), squeeze=False)
        fig.suptitle("EMVal 信号总览（左轴 价格/EMA，右轴 趋势/估值）", fontsize=13)

        for i, inst in enumerate(instruments):
            inst_row = i // ncols
            col = i % ncols
            ax_p = axes[inst_row][col]        # 左轴：价格 / EMA
            ax_r = ax_p.twinx()               # 右轴：趋势 / 估值

            inst_pred = pred_df.xs(inst, level="instrument")
            dates = inst_pred.index

            price_handles = []

            # --- 左轴：收盘价 + EMA_fast/EMA_mid/EMA_slow ---
            if close_wide is not None and inst in close_wide.columns:
                h, = ax_p.plot(dates, close_wide[inst].reindex(dates),
                               color="#212121", linewidth=0.25, label="Close")
                price_handles.append((h, "Close"))
            if "ema_fast" in inst_pred.columns:
                h, = ax_p.plot(dates, inst_pred["ema_fast"], color="#00ACC1",
                               linewidth=0.175, alpha=0.85, label="EMA_fast")
                price_handles.append((h, "EMA_fast"))
            if "ema_mid" in inst_pred.columns:
                h, = ax_p.plot(dates, inst_pred["ema_mid"], color="#7B1FA2",
                               linewidth=0.175, alpha=0.85, label="EMA_mid")
                price_handles.append((h, "EMA_mid"))
            if "ema_slow" in inst_pred.columns:
                h, = ax_p.plot(dates, inst_pred["ema_slow"], color="#E91E63",
                               linewidth=0.175, alpha=0.85, label="EMA_slow")
                price_handles.append((h, "EMA_slow"))

            # --- 左轴：score 背景着色 ---
            if "score" in inst_pred.columns:
                _fill_score_background(ax_p, dates, inst_pred["score"])

            ax_p.set_title(inst.replace("_CLEAN", ""), fontsize=8, pad=2)
            ax_p.set_ylabel("Price/EMA", fontsize=6)
            ax_p.tick_params(labelsize=5)
            ax_p.set_zorder(ax_r.get_zorder() + 1)   # 价格线置于右轴之上
            ax_p.patch.set_visible(False)            # 让右轴内容可见
            ax_p.xaxis.set_major_formatter(mdates.DateFormatter("%y-%m"))
            ax_p.xaxis.set_major_locator(mdates.AutoDateLocator())
            plt.setp(ax_p.xaxis.get_majorticklabels(), rotation=45, ha="right", fontsize=4)

            # --- 右轴：趋势 + 估值 ---
            right_handles = []
            if "diff" in inst_pred.columns:
                h, = ax_r.plot(dates, inst_pred["diff"], color="#3949AB",
                               linewidth=0.2, alpha=0.7, label="diff")
                right_handles.append((h, "diff"))
            if "over_val_pct" in inst_pred.columns:
                h, = ax_r.plot(dates, inst_pred["over_val_pct"], color="#FF9800",
                               linewidth=0.2, alpha=0.7, label="over_val_pct")
                right_handles.append((h, "over_val_pct"))
            if "over_val_rank" in inst_pred.columns:
                h, = ax_r.plot(dates, inst_pred["over_val_rank"], color="#4CAF50",
                               linewidth=0.2, alpha=0.7, label="over_val_rank")
                right_handles.append((h, "over_val_rank"))
                # 买入阈值线
                ax_r.axhline(y=self.buy_rank_thre, color="#4CAF50", linewidth=0.3,
                             linestyle="--", alpha=0.6)
                # 卖出阈值线
                ax_r.axhline(y=self.sell_rank_thre, color="#F44336", linewidth=0.3,
                             linestyle="--", alpha=0.6)

            ax_r.axhline(0, color="black", linewidth=0.4, alpha=0.5)
            ax_r.set_ylabel("Trend/Valuation", fontsize=6)
            ax_r.tick_params(labelsize=5)

            # 每个子图都绘制图例
            all_h = price_handles + right_handles
            if all_h:
                ax_p.legend([h for h, _ in all_h], [lb for _, lb in all_h],
                            fontsize=5, loc="upper left")

        # 隐藏多余子图
        for i in range(n, n_inst_rows * ncols):
            inst_row = i // ncols
            col = i % ncols
            axes[inst_row][col].set_visible(False)

        plt.tight_layout()

        artifact_uri = str(self.recorder.artifact_uri).replace("file://", "")
        save_root = os.path.join(artifact_uri, self.artifact_path)
        os.makedirs(save_root, exist_ok=True)
        save_path = os.path.join(save_root, "emval_overview.png")
        fig.savefig(save_path, dpi=120, bbox_inches="tight")
        plt.close(fig)
        logger.info(f"EMValChartRecord: saved overview chart → {save_path}")
        return {}

    def list(self):
        return []


class SignalDetailRecord(ACRecordTemp):
    """
    信号详细分析Record类，按股票保存每日信号详情到CSV文件
    
    为每只股票生成一个CSV文件，包含每天的pb、close、score、percentile等信息
    """

    artifact_path = "signal_detail"
    depend_cls = SignalRecord

    def __init__(self, recorder, skip_existing=False):
        super().__init__(recorder=recorder, skip_existing=skip_existing)

    def _generate(self, **kwargs):        
        # 设置中文字体支持
        rcParams['font.sans-serif'] = ['Arial Unicode MS', 'SimHei', 'DejaVu Sans']
        rcParams['axes.unicode_minus'] = False
        
        pred_df = self.load("pred.pkl")
        if pred_df.empty:
            logger.warning("Empty prediction data.")
            return {}

        # 获取artifact保存路径
        artifact_uri = str(self.recorder.artifact_uri).replace("file://", "")
        save_root = os.path.join(artifact_uri, self.artifact_path)
        os.makedirs(save_root, exist_ok=True)
        
        # 创建图片保存目录
        plot_root = os.path.join(save_root, "plots")
        os.makedirs(plot_root, exist_ok=True)

        # 按股票分组保存
        instruments = pred_df.index.get_level_values("instrument").unique()
        
        for inst in instruments:
            inst_data = pred_df.xs(inst, level="instrument")
            # 清理股票代码中的特殊字符，避免文件名问题
            safe_inst_name = str(inst).replace("/", "_").replace("\\", "_")
            
            # 保存CSV
            save_path = os.path.join(save_root, f"{safe_inst_name}.csv")
            inst_data.to_csv(save_path, index=True)
            
            # 生成可视化图片
            self._plot_instrument_signals(inst_data, inst, safe_inst_name, plot_root)
        
        logger.info(f"Saved {len(instruments)} instrument signal details to {save_root}")
        logger.info(f"Saved {len(instruments)} instrument plots to {plot_root}")
        
        # 同时保存一个汇总的CSV
        summary_path = os.path.join(save_root, "_all_signals.csv")
        pred_df.to_csv(summary_path, index=True)
        logger.info(f"Saved summary signal details to {summary_path}")
        
        return {}
    
    def _plot_instrument_signals(self, inst_data, inst, safe_inst_name, plot_root):
        """
        为单只股票生成可视化图片，展示各变量随时间的变化
        
        Parameters
        ----------
        inst_data : pd.DataFrame
            单只股票的数据，索引为datetime
        inst : str
            股票代码
        safe_inst_name : str
            清理后的股票代码（用于文件名）
        plot_root : str
            图片保存根目录
        """
        import matplotlib.pyplot as plt
        import matplotlib.dates as mdates
        
        # 获取所有可用的列
        available_cols = inst_data.columns.tolist()
        
        # 定义要绘制的变量及其配置
        plot_configs = []
        if 'score' in available_cols:
            plot_configs.append(('score', '信号得分', 'tab:blue', '-'))
        if 'percentile' in available_cols:
            plot_configs.append(('percentile', 'PB百分位', 'tab:orange', '-'))
        if 'current_pb' in available_cols:
            plot_configs.append(('current_pb', '当前PB', 'tab:green', '-'))
        if 'close' in available_cols:
            plot_configs.append(('close', '收盘价', 'tab:red', '-'))
        
        if len(plot_configs) == 0:
            logger.warning(f"No plottable columns found for {inst}")
            return
        
        # 创建图形，使用多个y轴共享x轴
        fig, host_ax = plt.subplots(figsize=(14, 8))
        fig.subplots_adjust(right=0.75)
        
        # 第一个变量使用主轴
        col_name, label, color, linestyle = plot_configs[0]
        host_ax.set_xlabel('日期', fontsize=12)
        host_ax.set_ylabel(label, color=color, fontsize=12)
        line1 = host_ax.plot(inst_data.index, inst_data[col_name], 
                             color=color, linestyle=linestyle, linewidth=1.5, label=label)
        host_ax.tick_params(axis='y', labelcolor=color)
        host_ax.grid(True, alpha=0.3)
        
        # 为其他变量创建额外的y轴
        axes = [host_ax]
        lines = line1
        
        for i, (col_name, label, color, linestyle) in enumerate(plot_configs[1:], start=1):
            # 创建新的y轴
            par_ax = host_ax.twinx()
            
            # 调整y轴位置，避免重叠
            if i > 1:
                par_ax.spines['right'].set_position(('outward', 60 * (i - 1)))
            
            par_ax.set_ylabel(label, color=color, fontsize=12)
            line = par_ax.plot(inst_data.index, inst_data[col_name], 
                              color=color, linestyle=linestyle, linewidth=1.5, label=label)
            par_ax.tick_params(axis='y', labelcolor=color)
            
            axes.append(par_ax)
            lines += line
        
        # 设置标题
        plt.title(f'{inst} - 信号指标时序变化', fontsize=14, pad=20)
        
        # 格式化x轴日期
        host_ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
        host_ax.xaxis.set_major_locator(mdates.AutoDateLocator())
        plt.setp(host_ax.xaxis.get_majorticklabels(), rotation=45, ha='right')
        
        # 添加图例
        labels = [l.get_label() for l in lines]
        host_ax.legend(lines, labels, loc='upper left', fontsize=10)
        
        # 保存图片
        plot_path = os.path.join(plot_root, f"{safe_inst_name}.png")
        plt.tight_layout()
        plt.savefig(plot_path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        
        logger.debug(f"Saved plot for {inst} to {plot_path}")

    def list(self):
        return []

