experiment:
    name: hist_rela_pb_tuner
    dir: examples/benchmarks/HistRelaPB/tuner_results
    tuner_class: WorkflowConfigTuner
    tuner_module_path: qlib.contrib.tuner.tuner

optimization_criteria:
    report_type: return_with_cost
    report_factor: annualized_return
    optim_type: max

tuner_pipeline:
  - workflow_config_path: examples/benchmarks/HistRelaPB/workflow_config.yaml
    workflow_experiment_name: hist_rela_pb_etf
    analysis_freq: 1day
    model:
        space: HistRelaPBModelSpace
    strategy:
        space: EvenWeightStrategySpace
    trainer: {}
    max_evals: 32

time_period: {}
data: {}
backtest: {}
qlib_client: {}
